
unset SERVER_SOFTWARE
unset SERVER_NAME
unset GATEWAY_INTERFACE
unset SERVER_PROTOCOL
unset SERVER_PORT
unset REQUEST_METHOD
unset PATH_INFO
unset PATH_TRANSLATED
unset SCRIPT_NAME
unset QUERY_STRING
unset REMOTE_HOST
unset REMOTE_ADDR
unset AUTH_TYPE
unset REMOTE_USER
unset REMOTE_IDENT
unset CONTENT_TYPE
unset CONTENT_LENGTH

export SERVER_SOFTWARE=SERVER_SOFTWARE
export SERVER_NAME=SERVER_NAME
export GATEWAY_INTERFACE=GATEWAY_INTERFACE
export SERVER_PROTOCOL=SERVER_PROTOCOL
export SERVER_PORT=SERVER_PORT
export REQUEST_METHOD=REQUEST_METHOD
export PATH_INFO=PATH_INFO
export PATH_TRANSLATED=PATH_TRANSLATED
export SCRIPT_NAME=SCRIPT_NAME
export QUERY_STRING=?QUERY_STRING?\\\\query\\\\?Test?a\\\\\\?a\\\\\\?a\\\\\\?
export REMOTE_HOST=REMOTE_HOST
export REMOTE_ADDR=REMOTE_ADDR
export AUTH_TYPE=AUTH_TYPE
export REMOTE_USER=REMOTE_USER
export REMOTE_IDENT=REMOTE_IDENT
export CONTENT_TYPE=CONTENT_TYPE
#export CONTENT_LENGTH=CONTENT_LENGTH

./CGITest
