
all:
	make -C ThreadObject -j
	make -C Exception -j
	make -C CGI -j

run:
	make -C ThreadObject run
	make -C Exception run
	make -C CGI run

clean:
	make -C ThreadObject clean
	make -C Exception clean
	make -C CGI clean
